try {
    console.log('Normal');
    
} catch(e){
    console.log('error');
}